//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Biit_Data
    {
        public string mobile_no { get; set; }
        public string name { get; set; }
        public string Email { get; set; }
        public string VerificationCode { get; set; }
        public string IsVerified { get; set; }
    }
}
