//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfService
{
    using System;
    using System.Collections.Generic;
    
    public partial class message_record
    {
        public int msgid { get; set; }
        public string from { get; set; }
        public string to { get; set; }
        public string msg { get; set; }
        public string msgstatus { get; set; }
    }
}
